### ISSUE TITLE
No Sonic 3 disassembly

### ISSUE THREAD

**Issue by Cleverking2003** [sonicretro/skdisasm#19]
Why don't we have a Sonic 3 disassembly? That's very strange and there seems to be no reason for that.

**Comment by Clownacy** [comment]
...Is this a joke?
1) [One was literally added a few days ago](https://github.com/sonicretro/skdisasm/pull/18)
2) 'No reason'? Do you have _any_ idea how effort it takes to make a (good) disassembly?

**Comment by fredbronze** [comment]
> Why don't we have a Sonic 3 disassembly? That's very strange and there seems to be no reason for that.

I know, right!?

> Do you have _any_ idea how much effort it takes to make a (good) disassembly?

No, but if you ever make one, please tell me cause I'm dying to know what it takes

**Comment by TheRetroSnake** [comment]
Its all lies, @fredbronze all you need to do, is open up IDA, press C and magically it apprears in front of you! The reason why it isn't added, is actually, because nobody has a Sonic 3 alone ROM and we have no way to rip it from carts.

**Comment by fredbronze** [comment]
I heard that because the Sonic 3 tape has a battery in it, all the bytes come out upside down and nobody knows how to get them back right side up.

**Comment by TheRetroSnake** [comment]
Maybe that is why the game keeps crashing all the time! Some of the bytes must be stuck upside-down, I see no other reason for it.

**Comment by Cleverking2003** [comment]
Well, you should actually update README when you do something that big, instead of being a shitty sarcastic person
