### ISSUE TITLE
Issues with "org $C71A0" in Sonic 3

### ISSUE THREAD

**Issue by Akrenix** [sonicretro/skdisasm#33]
So I've been trying to port FBZ into Sonic 3, but unfortunately, I always get an error due to the "org $C71A0" right before the sound data. I tried commenting this out but it caused issues. Any help would be greatly appreciated.

**Comment by TorutheRedFox** [comment]
S3K manages memory slightly differently to get around this

I remember I fixed it at one point, but don't remember how, so you have to go through comparing code I guess

plus, the collision data is a different format in S3 compared to S&K (S&K converts them on the fly when locked on), so you have to port the collision code over from S&K too

**Comment by Clownacy** [comment]
The `org $C71A0` was removed in 16b588fde29bb0677bd45dac171882bc0722a445, so this should no longer be an issue.
