### ISSUE TITLE
how do I use SONLVL with sonic 3 & knuckles

### ISSUE THREAD

**Issue by NickArcadeNerd** [sonicretro/skdisasm#51]
Sorry to waste your time, but how do I use SonLVL with sonic 3 and knuckles? When I try to build and run, it doesn't work and I cant find the log file, sorry 'bout that.

**Comment by MainMemory** [comment]
Looks like the build scripts got moved and nobody updated the SonLVL INI files. I've fixed the copies in this repository.

**Comment by NickArcadeNerd** [comment]
Thanks, you're the best!
