### ISSUE TITLE
ObjCheckLeftWallDist oddities

### ISSUE THREAD

**Issue by Leo40Git** [sonicretro/skdisasm#7]
This issue focuses on this one line: ``eori.w #$F,d3``
I find it odd that in S1 and S2's version of the routine, this line supposedly fixes erratic collision:
```
; Engine bug: colliding with left walls is erratic with this function.
; The cause is this: a missing instruction to flip collision on the found
; 16x16 block; this one:
;eori.w    #$F,d3
```
Yet in S&K's version of the routine, the line apparently _causes_ a bug:
```
eori.w    #$F,d3    ; this was not here in S1/S2, resulting in a bug
```
Is there a reason for this?

**Comment by flamewing** [comment]
While the comment is not as clear as it could have been, you are, nevertheless, misunderstanding it: the line was absent in S1/S2, causing a bug *in those games*.

**Comment by Leo40Git** [comment]
Ah, because of differences in level format I assume? Thanks for clearing it up.
